[workspace]
resolver = "2"
members = ["sils"]
default-members = ["sils"]

[workspace.package]
version = "4.5.1"
repository = "https://github.com/arkedge/c2a-core"

[workspace.lints.clippy]
pedantic = "warn"

[workspace.dependencies]
c2a-aobc-core-v4 = { path = "./" }
c2a-dev-runtime = { path = "src/src_core/dev-runtime" }
c2a-uart-kble = { path = "src/src_core/hal/uart-kble" }
c2a-wdt-noop = { path = "src/src_core/hal/wdt-noop" }

[lints]
workspace = true

[package]
name = "c2a-aobc-core-v4"
version = "0.1.0"
edition = "2021"

[dependencies]
c2a-core = "4.1.0"

[build-dependencies]
cmake = "0.1.50"
